version: '3.8'

services:
  # Milvus vector database
  milvus:
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    restart: unless-stopped

  # etcd for Milvus metadata storage
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: unless-stopped

  # MinIO for Milvus object storage
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    restart: unless-stopped

  # SFC-LLM Application
  sfc-llm:
    build: .
    ports:
      - "9001:9001"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - SFC_LLM_API_HOST=0.0.0.0
      - SFC_LLM_API_PORT=9001
      - SFC_LLM_EMBEDDING_DEVICE=cpu
      - SFC_LLM_API_PASSWORD=${SFC_LLM_API_PASSWORD:-kawallmshima}
      - SFC_LLM_API_REQUIRE_AUTH=${SFC_LLM_API_REQUIRE_AUTH:-true}
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    volumes:
      - ./models:/app/models
      - ./csvs:/app/csvs
      - milvus_db:/app/milvus_data
    depends_on:
      - milvus
    restart: unless-stopped

volumes:
  milvus_data:
  etcd_data:
  minio_data:
  milvus_db: